# Generated by Django 4.2.1 on 2023-05-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
