# Generated by Django 4.2.1 on 2023-06-05 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucr_app', '0002_rename_profile_picture_userprofile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='restaurant_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('images', models.ManyToManyField(related_name='photos', to='bucr_app.image')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bucr_app.restaurant')),
            ],
        ),
    ]
